services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  app:
    build: ./agent
    container_name: agent_app
    restart: always
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network: